### ISSUE TITLE
tsgen doesn't work

### ISSUE THREAD

**Issue by skyfranchittog** [contentstack/contentstack-cli-tsgen#1]
❯ csdx tsgen -a "delivery-token" -o "./contenstack/generated.d.ts"
Currently using NA region
    SyntaxError: '=>' expected. (38:16)
      36 | title: string;
      37 | /** Image Block */
    > 38 | image_block: ()[];
         |                ^
      39 | /** Banner Title */
      40 | banner_title?: string;
      41 | /** Banner Description */

This is the output of my tsgen. It stop working on image_block because of this non-speaking error.

**Comment by AniketDev7** [comment]
Hi @skyfranchittog    
Can u share which tsgen plugin and contentstack CLI version you have used ?
U can find the version using --help commands.
We checked with latest versions and were unable to replicate this at our end.
If possible can u try again with latest versions and see if its still occurring for you ?

cc: @netrajpatel

**Comment by cs-raj** [comment]
Closing the issue since there was no further communication 
cc: @netrajpatel @aman19K
