### ISSUE TITLE
Added "version" to global fields

### ISSUE THREAD

**Issue by neildan** [contentstack/contentstack-cli-tsgen#65]
In the last version of `contentstack-cli-tsgen`
The file `__generated__.types.ts` includes the field `version` on the global fields interfaces

**why you added `version` to global fields? is this intended?**

I've resolved that when I've installed a previous version
`csdx plugins:install contentstack-cli-tsgen@2.1.6`

**Comment by darekrossman** [comment]
Noticed this as well. Our content doesn't have `version`

**Comment by davorpeic** [comment]
Hi all, we have been working with Contentstack support and this issue has been fixed in the last v2.2.3 version, the proposal was to mark this field as optional so ot doesn't mess with how types are used. It solved out issue I hope it will yours too. 

dp

**Comment by cs-raj** [comment]
Closing the Issue since it was fixed
